# ThreadInstrument: Library to monitor thread activity
# Copyright (C) 2012-2017 Basilio B. Fraguela. Universidade da Coruna
#
# Distributed under the MIT License. (See accompanying file LICENSE)

# \file     Makefile
# \author   Basilio B. Fraguela <basilio.fraguela@udc.es>

all: doc

doc:
	doxygen Doxyfile

clean:
	-@rm -rf html latex

